# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest6product():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test6product(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.set_window_size(968, 906)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys(Keys.ENTER)
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#item_4_title_link > .inventory_item_name")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#item_0_title_link > .inventory_item_name")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#item_1_title_link > .inventory_item_name")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#item_5_title_link > .inventory_item_name")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#item_2_title_link > .inventory_item_name")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#item_3_title_link > .inventory_item_name")
    assert len(elements) > 0
  
